package dev.thaumcraft.test;

import dev.thaumcraft.content.Content;
import dev.thaumcraft.machine.*;
import net.minecraft.core.BlockPos;
import net.minecraft.core.Direction;
import net.minecraft.server.MinecraftServer;
import net.minecraft.server.level.ServerLevel;
import net.minecraft.world.level.block.Blocks;
import net.minecraft.world.item.ItemStack;
import net.minecraft.world.item.Items;
import net.minecraft.world.entity.item.ItemEntity;

/** Independent regression checks against original TileConduit, Tank, Pump, Filter and Purifier. */
public final class MachineParitySmokeTests {
    private static int checks;
    private static void check(boolean value,String message){checks++;if(!value)throw new AssertionError("Machine parity: "+message);}
    private static boolean near(float actual,float expected){return Math.abs(actual-expected)<.001f;}
    private static MachineBlockEntity place(ServerLevel level,BlockPos pos,String id){
        level.getChunkAt(pos);level.setBlockAndUpdate(pos,Blocks.AIR.defaultBlockState());
        level.setBlockAndUpdate(pos,Content.block(id).defaultBlockState());return (MachineBlockEntity)level.getBlockEntity(pos);
    }
    static int run(MinecraftServer server){
        checks=0;var level=server.overworld();var pos=new BlockPos(304,280,304);
        float[] mix=VisNetwork.mixedAmounts(1,9,4);check(near(mix[0],1)&&near(mix[1],3),"Mixed withdrawal uses remaining taint after pure shortage");
        mix=VisNetwork.mixedAmounts(9,1,4);check(near(mix[0],3)&&near(mix[1],1),"Mixed withdrawal uses remaining pure after taint shortage");
        mix=VisNetwork.mixedAmounts(10,10,4);check(near(mix[0],2)&&near(mix[1],2),"Mixed withdrawal splits equally");
        check(near(VisNetwork.mixedAmounts(10,10,Float.NaN)[0],0),"Invalid request cannot corrupt buffers");
        var source=place(level,pos,"crucible");source.insertVis(100,false);
        var bellowsPos=pos.east(40);
        place(level,bellowsPos.north(),"crucible");
        var bellowsContext=new net.minecraft.world.item.context.DirectionalPlaceContext(level,bellowsPos,Direction.UP,
                new ItemStack(Content.item("arcane_bellows")),Direction.SOUTH);
        var bellows=(MachineBlock)Content.block("arcane_bellows");
        check(bellows.getStateForPlacement(bellowsContext).getValue(MachineBlock.FACING)==Direction.NORTH,
                "Bellows face an adjacent crucible regardless of player heading");
        place(level,bellowsPos.west(),"arcane_furnace");
        check(bellows.getStateForPlacement(bellowsContext).getValue(MachineBlock.FACING)==Direction.WEST,
                "Original west neighbor takes priority when several valid machines surround bellows");
        level.setBlockAndUpdate(bellowsPos.north(),Blocks.AIR.defaultBlockState());
        level.setBlockAndUpdate(bellowsPos.west(),Blocks.AIR.defaultBlockState());
        var pipe=place(level,pos.east(),"vis_conduit");var consumer=place(level,pos.east(2),"thaumic_infuser");
        check(VisNetwork.pull(level,consumer,4,false)==0&&near(source.pureVis(),100),"Empty conduit cannot teleport remote source vis");
        VisNetwork.tick(level,pipe);check(pipe.visSuction()==49&&pipe.taintSuction()==0,"Demand propagates pure suction 50 to 49 only");
        check(near(pipe.pureVis(),4)&&near(source.pureVis(),96),"Conduit stores bounded local transfer");
        check(near(VisNetwork.pull(level,consumer,4,false),4)&&near(pipe.pureVis(),0),"Consumer drains adjacent conduit buffer");
        var blocked=place(level,pos.above(),"thaumic_infuser");check(VisNetwork.pull(level,blocked,4,false)==0,"Crucible upper face cannot connect");
        var valve=place(level,pos.south(3),"vis_valve");check(!valve.enabled(),"Original valve starts closed");valve.toggle();check(valve.enabled(),"Manual valve opens");
        var tank=place(level,pos.south(6),"vis_storage_tank");var upper=place(level,pos.south(6).above(),"thaumium_reinforced_tank");
        check(tank.capacity()==500&&upper.capacity()==1000,"Original glass and reinforced tank capacities");
        for(var machine:new MachineBlockEntity[]{tank,upper}){
            var hit=new net.minecraft.world.phys.BlockHitResult(net.minecraft.world.phys.Vec3.atBottomCenterOf(machine.getBlockPos().above()),Direction.UP,machine.getBlockPos(),false);
            var state=machine.getBlockState();
            check(state.useWithoutItem(level,null,hit)==net.minecraft.world.InteractionResult.PASS,"Tank right-click falls through to held block item");
        }
        upper.insertVis(300,false);upper.insertVis(300,true);VisNetwork.tick(level,tank);
        check(near(tank.pureVis(),250)&&near(tank.taintedVis(),250)&&near(upper.totalVis(),100),"Stack fills bottom first while retaining mixture ratio");
        var purifier=place(level,pos.south(9),"vis_purifier");purifier.insertVis(1,true);VisNetwork.tick(level,purifier);
        check(near(purifier.taintedVis(),.99f)&&near(purifier.pureVis(),0)&&purifier.taintSuction()==5,"Purifier destroys .01 taint per tick without creating pure vis");
        var filter=place(level,pos.south(12),"vis_filter");filter.insertVis(1,true);VisNetwork.tick(level,filter);
        check(filter.taintSuction()==15&&near(filter.taintedVis(),.975f),"Filter requests taint and collects .025 per tick");
        var pump=place(level,pos.south(15),"vis_pump");level.setBlockAndUpdate(pump.getBlockPos(),pump.getBlockState().setValue(MachineBlock.FACING,Direction.EAST));VisNetwork.tick(level,pump);
        check(VisNetwork.suctionFrom(pump,pump.getBlockPos().east(),false)==20&&VisNetwork.suctionFrom(pump,pump.getBlockPos().west(),false)==0,"Pump exposes suction on intake face only");
        var atomic=place(level,pos.south(18),"thaumic_generator");
        var left=place(level,atomic.getBlockPos().west(),"vis_conduit");var right=place(level,atomic.getBlockPos().east(),"vis_conduit");left.insertVis(.01f,false);right.insertVis(.01f,false);
        check(!VisNetwork.takeExactPure(level,atomic,.015f)&&near(left.pureVis(),.01f)&&near(right.pureVis(),.01f),"Exact vis request never combines insufficient adjacent buffers");
        left.insertVis(.1f,false);MachineLogic.generator(level,atomic);check(atomic.energy()>0,"Moon-dependent generator produces energy from adjacent source");
        var condenser=place(level,pos.south(21),"vis_condenser");var condenser2=place(level,pos.south(21).east(),"vis_condenser");
        condenser.insertVis(10,false);condenser.insertVis(10,true);VisNetwork.equalizeCondensers(level,condenser);
        check(condenser.capacity()==10&&near(condenser.pureVis(),5)&&near(condenser.taintedVis(),5)&&near(condenser2.totalVis(),10),"Condensers retain separate ten-vis component capacities and share neighbors equally");
        var dark=place(level,pos.south(24),"darkness_generator");dark.setItem(0,new ItemStack(Items.WHEAT_SEEDS));MachineLogic.darkness(level,dark);
        check(dark.progress==0&&dark.getItem(9).isEmpty(),"Dark generator requires nearby monolith");
        level.setBlockAndUpdate(dark.getBlockPos().east(),Content.block("eldritch_monolith").defaultBlockState());dark.progress=89999;long darknessTime=level.getGameTime();((net.minecraft.world.level.storage.ServerLevelData)level.getLevelData()).setGameTime(darknessTime+20);MachineLogic.darkness(level,dark);((net.minecraft.world.level.storage.ServerLevelData)level.getLevelData()).setGameTime(darknessTime);
        check(dark.getItem(0).isEmpty()&&dark.getItem(9).is(Content.item("seed_of_darkness")),"Dark generator consumes a seed at 90000 work and exposes its output slot");
        check(MachineLayout.get("darkness_generator").cells().size()==2&&MachineLayout.get("darkness_generator").texture().equals("guidarkgen"),"Dark generator restores original two-slot screen");
        var crucible=place(level,pos.south(27),"crucible");var dropped=new ItemEntity(level,crucible.getBlockPos().getX()+.5,crucible.getBlockPos().getY()+.6,crucible.getBlockPos().getZ()+.5,new ItemStack(Items.COBBLESTONE));level.addFreshEntity(dropped);
        float value=dev.thaumcraft.gameplay.GameData.vis(dropped.getItem());MachineLogic.crucible(level,crucible);
        check(value>0&&!dropped.isAlive()&&near(crucible.pureVis(),value*.5f)&&near(crucible.taintedVis(),value*.5f),"Crucible processes physical contents using its original fifty-percent conversion");
        var damaged=new ItemStack(Items.COBBLESTONE);
        damaged.set(net.minecraft.core.component.DataComponents.MAX_DAMAGE,100);damaged.setDamageValue(1);
        var rejected=new ItemEntity(level,crucible.getBlockPos().getX()+.5,crucible.getBlockPos().getY()+.6,crucible.getBlockPos().getZ()+.5,damaged);level.addFreshEntity(rejected);
        float beforeDamageCheck=crucible.totalVis();for(int i=0;i<30;i++)MachineLogic.crucible(level,crucible);
        check(dev.thaumcraft.gameplay.GameData.vis(damaged)>0&&rejected.isAlive()&&rejected.getItem().getCount()==1&&crucible.totalVis()==beforeDamageCheck,"Crucible rejects damaged items even with an explicit positive vis value");rejected.discard();
        var souls=place(level,pos.south(30),"crucible_of_souls");var ignored=new ItemEntity(level,souls.getBlockPos().getX()+.5,souls.getBlockPos().getY()+.6,souls.getBlockPos().getZ()+.5,new ItemStack(Items.COBBLESTONE));level.addFreshEntity(ignored);MachineLogic.crucible(level,souls);
        check(ignored.isAlive()&&souls.totalVis()==0,"Soul crucible never smelts dropped items");ignored.discard();
        check(java.util.Arrays.equals(condenser.getSlotsForFace(Direction.DOWN),new int[]{9})&&java.util.Arrays.equals(condenser.getSlotsForFace(Direction.UP),new int[]{0}),"Condenser bottom exposes output and top exposes crystal input");
        var furnace=place(level,pos.south(33),"arcane_furnace");check(java.util.Arrays.equals(furnace.getSlotsForFace(Direction.DOWN),new int[]{MachineBlockEntity.FUEL_SLOT})&&furnace.getSlotsForFace(Direction.UP)[0]==9&&furnace.getSlotsForFace(Direction.NORTH)[0]==0,"Original furnace automation uses bottom fuel, top output and horizontal inputs");
        check(consumer.getSlotsForFace(Direction.DOWN).length==6&&java.util.Arrays.equals(consumer.getSlotsForFace(Direction.EAST),new int[]{9,10}),"Infuser automation exposes ingredients vertically and results horizontally");
        var repeated=new dev.thaumcraft.gameplay.GameData.Infusion(new dev.thaumcraft.gameplay.GameData.StackDef("minecraft:stone",1),1,java.util.List.of("minecraft:iron_ingot","minecraft:iron_ingot"),false,-1);
        var single=new java.util.ArrayList<ItemStack>();single.add(new ItemStack(Items.IRON_INGOT,2));single.add(ItemStack.EMPTY);while(single.size()<6)single.add(ItemStack.EMPTY);
        check(dev.thaumcraft.gameplay.GameData.allocateNormal(repeated,single,2)==null,"Normal infusion rejects a single stack of two for two identical ingredients");
        var split=new java.util.ArrayList<ItemStack>();split.add(new ItemStack(Items.IRON_INGOT,2));split.add(new ItemStack(Items.IRON_INGOT,1));while(split.size()<6)split.add(ItemStack.EMPTY);
        int[] splitUsed=dev.thaumcraft.gameplay.GameData.allocateNormal(repeated,split,2);
        check(splitUsed!=null&&splitUsed[0]==1&&splitUsed[1]==1,"Normal infusion splits identical ingredients across two slots consuming one each");
        var unrelated=new java.util.ArrayList<ItemStack>(split);unrelated.set(2,new ItemStack(Items.DIRT));
        check(dev.thaumcraft.gameplay.GameData.allocateNormal(repeated,unrelated,6)==null,"Normal infusion rejects unrelated occupied slots");
        var missing=new java.util.ArrayList<ItemStack>();missing.add(new ItemStack(Items.IRON_INGOT));missing.add(ItemStack.EMPTY);while(missing.size()<6)missing.add(ItemStack.EMPTY);
        check(dev.thaumcraft.gameplay.GameData.allocateNormal(repeated,missing,2)==null,"Normal infusion rejects missing ingredients");
        var clothTag=net.minecraft.tags.TagKey.create(net.minecraft.core.registries.Registries.ITEM,net.minecraft.resources.Identifier.parse("thaumcraft2tp:legacy/cloth"));
        var clothItem=net.minecraft.core.registries.BuiltInRegistries.ITEM.get(clothTag).orElseThrow().iterator().next().value();
        var wildRecipe=new dev.thaumcraft.gameplay.GameData.Infusion(new dev.thaumcraft.gameplay.GameData.StackDef("minecraft:stone",1),1,java.util.List.of("#thaumcraft2tp:legacy/cloth"),false,-1);
        var wildInputs=new java.util.ArrayList<ItemStack>();wildInputs.add(new ItemStack(clothItem));while(wildInputs.size()<6)wildInputs.add(ItemStack.EMPTY);
        check(dev.thaumcraft.gameplay.GameData.allocateNormal(wildRecipe,wildInputs,1)!=null,"Normal infusion retains wildcard matching");
        var ingotRecipe=dev.thaumcraft.gameplay.GameData.infusions().stream().filter(r->!r.dark()&&r.research()<0&&r.result().id().equals("thaumcraft2tp:thaumium_ingot")).findFirst().orElseThrow();
        for(int i=0;i<6;i++)consumer.setItem(i,ItemStack.EMPTY);consumer.setItem(9,ItemStack.EMPTY);consumer.setItem(10,ItemStack.EMPTY);
        consumer.setItem(0,new ItemStack(Content.item("vis_crystal"),3));consumer.setItem(1,new ItemStack(Items.IRON_INGOT,2));
        consumer.insertVis(ingotRecipe.cost(),false);
        for(int i=0;i<ingotRecipe.cost()*2+5;i++)consumer.processes.tick(level);
        check(consumer.getItem(9).is(Content.item("thaumium_ingot"))&&consumer.getItem(9).getCount()==ingotRecipe.result().count(),"Infuser produces exact result count");
        check(consumer.getItem(0).getCount()==2&&consumer.getItem(1).getCount()==1,"Infuser consumes exactly one from each ingredient slot");
        var depleted=consumer.getItem(10);
        check(depleted.isEmpty()||(depleted.is(Content.item("depleted_crystal"))&&depleted.getCount()<=1),"Infuser crystal byproduct is depleted or empty");
        for(int i=0;i<6;i++)consumer.setItem(i,ItemStack.EMPTY);consumer.setItem(9,ItemStack.EMPTY);consumer.setItem(10,ItemStack.EMPTY);
        var isolated=place(level,pos.south(45),"thaumic_infuser");
        isolated.processes.boost=0;
        isolated.setItem(0,new ItemStack(Items.GLOWSTONE_DUST,2));isolated.setItem(1,new ItemStack(Items.REDSTONE,2));
        for(int i=2;i<6;i++)isolated.setItem(i,ItemStack.EMPTY);
        isolated.setItem(9,ItemStack.EMPTY);isolated.setItem(10,ItemStack.EMPTY);
        isolated.processes.tick(level);
        check(isolated.processes.pureCost==10&&isolated.processes.pureWork==0,"Infuser initializes cost before absorbing");
        isolated.insertVis(10,false);isolated.processes.boost=0;
        for(int i=0;i<5;i++)isolated.processes.tick(level);
        check(isolated.processes.pureWork>0&&isolated.processes.pureWork<10,"Infuser makes partial progress");
        check(isolated.getItem(9).isEmpty()&&isolated.getItem(0).getCount()==2,"Partial progress consumes nothing");
        float savedWork=isolated.processes.pureWork;
        isolated.setItem(0,new ItemStack(Content.item("alumentum")));isolated.setItem(1,new ItemStack(Content.item("nitor")));
        isolated.processes.tick(level);
        check(isolated.processes.pureWork>=savedWork&&isolated.processes.pureCost==10,"Equal-cost recipe replacement preserves progress");
        isolated.setItem(0,new ItemStack(Content.item("vis_crystal")));isolated.setItem(1,new ItemStack(Items.IRON_INGOT));
        isolated.processes.tick(level);
        check(isolated.processes.pureWork==0,"Changed cost clears progress");
        for(int i=2;i<6;i++)isolated.setItem(i,ItemStack.EMPTY);
        isolated.setItem(0,new ItemStack(Items.GLOWSTONE_DUST,2));isolated.setItem(1,new ItemStack(Items.REDSTONE,2));
        isolated.setItem(9,ItemStack.EMPTY);isolated.setItem(10,ItemStack.EMPTY);
        isolated.extractVis(isolated.pureVis(),false);
        isolated.processes.tick(level);
        isolated.extractVis(isolated.pureVis(),false);
        isolated.insertVis(10,false);isolated.processes.boost=0;
        float beforeCraft=isolated.pureVis();
        for(int i=0;i<40;i++)isolated.processes.tick(level);
        check(isolated.getItem(9).is(Content.item("nitor"))&&isolated.getItem(9).getCount()==1,"Infuser completes with exact result");
        check(isolated.getItem(0).getCount()==1&&isolated.getItem(1).getCount()==1,"Completion consumes one per slot");
        check(Math.abs((beforeCraft-isolated.pureVis())-10)<=0.02f,"Infuser vis consumption allows 0.01 overdraw");
        isolated.setItem(9,new ItemStack(Items.DIRT,5));
        int blocked0=isolated.getItem(0).getCount(),blocked1=isolated.getItem(1).getCount();
        isolated.insertVis(10,false);
        for(int i=0;i<5;i++)isolated.processes.tick(level);
        check(isolated.getItem(0).getCount()==blocked0&&isolated.getItem(1).getCount()==blocked1&&!isolated.getItem(9).is(Content.item("nitor")),"Blocked output consumes nothing");
        isolated.setItem(9,ItemStack.EMPTY);
        isolated.extractVis(isolated.pureVis(),false);
        blocked0=isolated.getItem(0).getCount();blocked1=isolated.getItem(1).getCount();
        for(int i=0;i<5;i++)isolated.processes.tick(level);
        check(isolated.getItem(9).isEmpty()&&isolated.getItem(0).getCount()==blocked0,"Empty vis creates nothing");
        isolated.insertVis(10,false);
        for(int i=0;i<2;i++)isolated.processes.tick(level);
        for(int i=0;i<6;i++)isolated.setItem(i,ItemStack.EMPTY);
        isolated.processes.tick(level);
        check(isolated.processes.pureWork==0&&isolated.processes.pureCost==0&&isolated.getItem(9).isEmpty(),"Clearing inputs never creates stale output");
        isolated.setItem(0,new ItemStack(Items.GLOWSTONE_DUST,2));isolated.setItem(1,new ItemStack(Items.REDSTONE,2));
        isolated.setItem(9,ItemStack.EMPTY);isolated.extractVis(isolated.pureVis(),false);isolated.insertVis(10,false);isolated.processes.boost=0;
        isolated.processes.tick(level);isolated.processes.tick(level);
        float poweredWork=isolated.processes.pureWork;float poweredVis=isolated.pureVis();
        check(poweredWork>0,"Powered test starts with progress");
        level.setBlockAndUpdate(isolated.getBlockPos().above(),Blocks.REDSTONE_BLOCK.defaultBlockState());
        for(int i=0;i<5;i++)isolated.processes.tick(level);
        check(isolated.processes.pureWork==poweredWork&&isolated.pureVis()==poweredVis,"Powering unchanged recipe retains progress without consumption");
        isolated.setItem(0,new ItemStack(Content.item("vis_crystal")));isolated.setItem(1,new ItemStack(Items.IRON_INGOT));
        isolated.processes.tick(level);
        check(isolated.processes.pureWork==0,"Powered recipe change invalidates immediately");
        level.setBlockAndUpdate(isolated.getBlockPos().above(),Blocks.AIR.defaultBlockState());
        isolated.setItem(0,new ItemStack(Items.GLOWSTONE_DUST,2));isolated.setItem(1,new ItemStack(Items.REDSTONE,2));
        isolated.setItem(9,ItemStack.EMPTY);isolated.extractVis(isolated.pureVis(),false);isolated.processes.tick(level);
        isolated.extractVis(isolated.pureVis(),false);isolated.insertVis(12,false);isolated.processes.boost=0;
        isolated.processes.tick(level);isolated.processes.tick(level);isolated.processes.tick(level);
        isolated.processes.recipeKey="thaumcraft2tp:nitor"; // Legacy saves used the output item ID.
        var savedInfusion=isolated.saveWithFullMetadata(level.registryAccess());
        savedInfusion.remove("work_definition");
        var reloadedInfusion=(MachineBlockEntity)net.minecraft.world.level.block.entity.BlockEntity.loadStatic(isolated.getBlockPos(),isolated.getBlockState(),savedInfusion,level.registryAccess());
        check(reloadedInfusion!=null&&reloadedInfusion.processes.pureWork>0&&reloadedInfusion.processes.pureCost==10,"Save/reload preserves partial infusion");
        float restoredWork=reloadedInfusion.processes.pureWork,restoredVis=reloadedInfusion.pureVis();
        level.removeBlockEntity(isolated.getBlockPos());level.setBlockEntity(reloadedInfusion);
        reloadedInfusion.processes.tick(level);
        check(reloadedInfusion.processes.recipeKey.equals("thaumcraft2tp:infusion/nitor")&&reloadedInfusion.processes.pureWork>=restoredWork,"Legacy infusion key migrates without losing paid work");
        for(int i=0;i<40&&reloadedInfusion.getItem(9).isEmpty();i++)reloadedInfusion.processes.tick(level);
        check(reloadedInfusion.getItem(9).is(Content.item("nitor"))&&reloadedInfusion.getItem(9).getCount()==1,"Reloaded infusion continues to completion");
        check(reloadedInfusion.getItem(0).getCount()==1&&reloadedInfusion.getItem(1).getCount()==1,"Reloaded infusion consumes one of each ingredient");
        check(Math.abs(restoredVis-reloadedInfusion.pureVis()-(10-restoredWork))<=.011f,"Reloaded infusion spends only remaining vis");
        check(isolated.getItem(9).isEmpty(),"Reload continuation does not tick the detached original machine");
        level.setBlockAndUpdate(pos.south(45),Blocks.AIR.defaultBlockState());
        var boostA=place(level,pos.south(46),"thaumic_infuser");
        var boostB=place(level,pos.south(47),"thaumic_infuser");
        var auraBoost=dev.thaumcraft.gameplay.ArcaneWorldData.get(level);
        boostA.setItem(0,new ItemStack(Items.GLOWSTONE_DUST,2));boostA.setItem(1,new ItemStack(Items.REDSTONE,2));
        boostA.processes.tick(level);boostA.insertVis(20,false);
        auraBoost.changeBoost(level,boostA.getBlockPos(),100);
        boostA.processes.boost=0;boostA.processes.infuserBoostDelay=10;
        boostA.processes.tick(level);
        check(near(boostA.processes.infuserAbsorbed,.5f)&&boostA.processes.boost==1,"Boost acquisition affects the next craft tick, not the current one");
        boostA.processes.tick(level);
        check(near(boostA.processes.infuserAbsorbed,.55f),"Craft tick following acquisition uses the new boost");
        auraBoost.changeBoost(level,boostA.getBlockPos(),-1000);
        boostA.processes.boost=3;boostA.processes.infuserBoostDelay=0;
        boostA.processes.tick(level);
        check(near(boostA.processes.infuserAbsorbed,.65f)&&boostA.processes.boost==2,"Boost decay affects the next craft tick, not the current one");
        boostA.processes.tick(level);
        check(near(boostA.processes.infuserAbsorbed,.6f),"Craft tick following decay uses the new boost");
        boostA.setItem(0,ItemStack.EMPTY);boostA.setItem(1,ItemStack.EMPTY);boostA.processes.clearWork();
        auraBoost.changeBoost(level,boostA.getBlockPos(),100);auraBoost.changeBoost(level,boostB.getBlockPos(),100);
        boostA.processes.boost=0;boostA.processes.infuserBoostDelay=20;
        for(int i=0;i<21;i++)boostA.processes.tick(level);
        check(boostA.processes.boost==1&&boostA.processes.infuserBoostDelay==20,"Infuser boost follows 21-tick acquire-decay cycle");
        auraBoost.changeBoost(level,boostB.getBlockPos(),-100);
        boostB.processes.boost=3;boostB.processes.infuserBoostDelay=20;
        for(int i=0;i<21;i++)boostB.processes.tick(level);
        check(boostB.processes.boost==2&&boostB.processes.infuserBoostDelay==20,"Exhausted aura still decays boost on schedule");
        auraBoost.changeBoost(level,boostA.getBlockPos(),100);
        boostA.processes.boost=10;boostA.processes.infuserBoostDelay=0;
        boostA.processes.tick(level);
        check(boostA.processes.boost==9&&boostA.processes.infuserBoostDelay==20,"Boost caps at 10 with acquire-before-decay");
        boostA.processes.boost=0;boostA.processes.infuserBoostDelay=10;
        boostB.processes.boost=0;boostB.processes.infuserBoostDelay=5;
        auraBoost.changeBoost(level,boostA.getBlockPos(),100);auraBoost.changeBoost(level,boostB.getBlockPos(),100);
        boostA.processes.tick(level);boostB.processes.tick(level);
        check(boostA.processes.boost==1&&boostB.processes.boost==0,"Local boost timing is independent of world-time phase");
        boostA.setItem(0,new ItemStack(Items.GLOWSTONE_DUST,2));boostA.setItem(1,new ItemStack(Items.REDSTONE,2));
        boostA.processes.boost=7;boostA.insertVis(5,false);
        boostA.processes.tick(level);
        var savedBoostState=boostA.saveWithFullMetadata(level.registryAccess());
        var reloadedBoost=(MachineBlockEntity)net.minecraft.world.level.block.entity.BlockEntity.loadStatic(boostA.getBlockPos(),boostA.getBlockState(),savedBoostState,level.registryAccess());
        check(reloadedBoost!=null&&reloadedBoost.processes.boost==0,"Infuser boost is transient on reload");
        check(!reloadedBoost.getItem(0).isEmpty()&&reloadedBoost.processes.pureCost==10,"Reload preserves inventory and progress without old boost");
        level.setBlockAndUpdate(pos.south(46),Blocks.AIR.defaultBlockState());
        level.setBlockAndUpdate(pos.south(47),Blocks.AIR.defaultBlockState());
        var visual=place(level,pos.south(48),"thaumic_infuser");
        visual.setItem(0,new ItemStack(Items.GLOWSTONE_DUST,2));visual.setItem(1,new ItemStack(Items.REDSTONE,2));
        for(int i=2;i<6;i++)visual.setItem(i,ItemStack.EMPTY);
        visual.setItem(9,ItemStack.EMPTY);visual.setItem(10,ItemStack.EMPTY);
        visual.processes.tick(level);
        visual.extractVis(visual.pureVis(),false);visual.insertVis(10,false);visual.processes.boost=0;
        visual.processes.tick(level);visual.processes.tick(level);
        check(visual.processes.infuserAbsorbed>0,"Infuser publishes absorption while working");
        visual.extractVis(visual.pureVis(),false);
        visual.processes.tick(level);
        check(visual.processes.infuserAbsorbed==0,"Starved infuser clears absorption");
        check(visual.getUpdateTag(level.registryAccess()).getBooleanOr("infuser_processing",false),"Starved valid infusion still permits upgrade flames");
        visual.insertVis(10,false);
        visual.processes.tick(level);
        check(visual.processes.infuserAbsorbed>0,"Infuser resumes absorption");
        level.setBlockAndUpdate(visual.getBlockPos().above(),Blocks.REDSTONE_BLOCK.defaultBlockState());
        float visualVis=visual.pureVis();
        visual.processes.tick(level);
        check(visual.processes.infuserAbsorbed==0&&visual.pureVis()==visualVis,"Powered infuser clears absorption without consumption");
        check(!visual.getUpdateTag(level.registryAccess()).getBooleanOr("infuser_processing",true),"Powered infusion stops upgrade flames");
        level.setBlockAndUpdate(visual.getBlockPos().above(),Blocks.AIR.defaultBlockState());
        visual.setItem(9,new ItemStack(Items.DIRT,5));
        visual.processes.tick(level);
        check(visual.processes.infuserAbsorbed==0,"Blocked infuser clears absorption");
        check(!visual.getUpdateTag(level.registryAccess()).getBooleanOr("infuser_processing",true),"Blocked output stops upgrade flames despite retained progress");
        visual.setItem(9,ItemStack.EMPTY);
        for(int i=0;i<6;i++)visual.setItem(i,ItemStack.EMPTY);
        visual.processes.tick(level);
        check(visual.processes.infuserAbsorbed==0,"Idle infuser clears absorption");
        visual.setItem(0,new ItemStack(Items.GLOWSTONE_DUST,2));visual.setItem(1,new ItemStack(Items.REDSTONE,2));
        visual.setItem(9,ItemStack.EMPTY);visual.extractVis(visual.pureVis(),false);visual.processes.tick(level);
        visual.extractVis(visual.pureVis(),false);visual.insertVis(10,false);visual.processes.boost=0;
        boolean sawAbsorption=false;
        for(int i=0;i<40&&!sawAbsorption;i++) {
            boolean hadOutput=!visual.getItem(9).isEmpty();
            visual.processes.tick(level);
            if(!hadOutput&&!visual.getItem(9).isEmpty()) {
                check(visual.processes.infuserAbsorbed>0&&visual.processes.pureWork==0,"Last craft tick keeps absorption after progress resets");
                sawAbsorption=true;
            }
        }
        check(sawAbsorption,"Infuser completed for absorption check");
        visual.insertVis(10,false);
        boolean sawLastUnit=false;
        for(int i=0;i<40&&!sawLastUnit;i++) {
            int before=visual.getItem(9).getCount();
            visual.processes.tick(level);
            if(visual.getItem(9).getCount()==before+1) {
                check(visual.processes.pureCost==0,"Last-ingredient completion leaves no phantom cost");
                sawLastUnit=true;
            }
        }
        check(sawLastUnit,"Infuser completed on last ingredients");
        level.setBlockAndUpdate(pos.south(48),Blocks.AIR.defaultBlockState());
        var enchanter=place(level,pos.south(36),"thaumic_enchanter");check(enchanter.canTakeItemThroughFace(0,new ItemStack(Items.IRON_PICKAXE),Direction.DOWN),"Enchanter result in input slot can be extracted by automation");
        var brazier=place(level,pos.east(64),"brazier_of_souls");
        check(brazier.canPlaceItem(0,new ItemStack(Content.item("soul_fragment")))&&!brazier.canPlaceItem(0,new ItemStack(Items.COAL)),"Soul brazier accepts only soul fragments");
        for(var face:Direction.values())check(java.util.Arrays.equals(brazier.getSlotsForFace(face),new int[]{0}),"Soul brazier exposes its one fuel slot on "+face);
        var aura=dev.thaumcraft.gameplay.ArcaneWorldData.get(level);var local=aura.aura(level,brazier.getBlockPos());aura.changeAura(level,brazier.getBlockPos(),-local.vis(),-local.taint());
        for(var face:Direction.Plane.HORIZONTAL){var neighbor=brazier.getBlockPos().relative(face,16);level.getChunkAt(neighbor);var cell=aura.aura(level,neighbor);aura.changeAura(level,neighbor,-cell.vis(),100-cell.taint());}
        brazier.setItem(0,new ItemStack(Content.item("soul_fragment"),2));brazier.processes.tick(level);
        check(brazier.processes.burnTime==5999&&brazier.getItem(0).getCount()==1,"Soul brazier consumes one fragment for 6000 ticks and burns the first tick immediately");
        check(near(aura.aura(level,brazier.getBlockPos()).taint(),1)&&near(aura.aura(level,brazier.getBlockPos()).vis(),0),"Soul brazier falls back to one taint when neighboring pure aura is empty");
        level.setBlockAndUpdate(brazier.getBlockPos().above(),Blocks.REDSTONE_BLOCK.defaultBlockState());brazier.processes.tick(level);
        check(brazier.processes.burnTime==5999&&brazier.getItem(0).getCount()==1,"Redstone pauses soul fuel without consuming another fragment");
        var saved=brazier.saveWithFullMetadata(level.registryAccess());var restored=(MachineBlockEntity)net.minecraft.world.level.block.entity.BlockEntity.loadStatic(brazier.getBlockPos(),brazier.getBlockState(),saved,level.registryAccess());
        check(restored!=null&&restored.processes.burnTime==5999&&restored.getItem(0).getCount()==1,"Soul brazier fuel and remaining burn time survive persistence");
        level.setBlockAndUpdate(brazier.getBlockPos().above(),Blocks.AIR.defaultBlockState());level.setBlockAndUpdate(brazier.getBlockPos(),Blocks.AIR.defaultBlockState());
        var urn=place(level,pos.east(64),"everfull_urn");urn.setItem(0,new ItemStack(Items.BUCKET));for(int i=0;i<12;i++)MachineLogic.tick(level,urn);
        check(urn.getItem(0).is(Items.BUCKET)&&urn.getItem(9).isEmpty()&&urn.getSlotsForFace(Direction.UP).length==0,"Original urn has no hidden inventory processing or hopper slots");
        level.setBlockAndUpdate(urn.getBlockPos(),Blocks.AIR.defaultBlockState());
        var brain=place(level,pos.east(64),"brain_in_a_jar");net.minecraft.world.entity.ExperienceOrb.award(level,net.minecraft.world.phys.Vec3.atCenterOf(brain.getBlockPos()).add(0,1,0),5);
        var orbs=level.getEntitiesOfClass(net.minecraft.world.entity.ExperienceOrb.class,new net.minecraft.world.phys.AABB(brain.getBlockPos()).inflate(2));for(int i=0;i<8;i++)MachineLogic.tick(level,brain);
        check(!orbs.isEmpty()&&orbs.stream().allMatch(net.minecraft.world.entity.Entity::isAlive)&&brain.energy()==0,"Original decorative brain leaves experience orbs untouched");orbs.forEach(net.minecraft.world.entity.Entity::discard);
        level.setBlockAndUpdate(brain.getBlockPos(),Blocks.AIR.defaultBlockState());
        for(int x=-1;x<=3;x++)for(int z=-1;z<=37;z++)for(int y=0;y<=1;y++)level.setBlockAndUpdate(pos.offset(x,y,z),Blocks.AIR.defaultBlockState());
        return checks+IntegrationSmokeTests.run(server)+SealParitySmokeTests.run(server);
    }
}
